server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

spring:
  application:
    name: Provider8001

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.example.provider8001.entity
  mapperLocations: classpath:mapper/*.xml